+incdir+design/digital/rtl
design/digital/rtl/core/snn_ecg_input_normalizer.v
design/digital/rtl/core/ecg_event_encoder_adaptive.v
design/digital/rtl/core/qrs_lif_detector.v
design/digital/rtl/core/pnn_rhythm_predictor.v
design/digital/rtl/core/dscr_spike_counter.v
design/digital/rtl/core/ram_peak_accumulator.v
design/digital/rtl/core/rdm_variability_neuron.v
design/digital/rtl/core/ectopic_pair_neuron.v
design/digital/rtl/core/qrs_maf_neuron.v
design/digital/rtl/core/rbbb_qrs_delay_bank.v
design/digital/rtl/core/class_score_neurons.v
design/digital/rtl/core/abandoned_feature_stubs.v
design/digital/rtl/core/snn_ecg_3feat_top.v
design/digital/rtl/final_membrane_layer.v
design/digital/rtl/snn_ecg_30min_final_top.v
design/digital/asic/gpdk45/rtl/snn_ecg_asic_core_top.v
design/digital/asic/gpdk45/sim/tb_snn_ecg_asic_power_prefix.v
